### ISSUE TITLE
Error InvalidArgumentException class does not exist.

### ISSUE THREAD

**Issue by aaron-capellic** [minnur/Alter-Entity-Autocomplete#2]
I'm getting this error:

```InvalidArgumentException: Class "\Drupal\alter_entity_autocomplete\Controller\EntityAutocompleteController" does not exist. in Drupal\Core\DependencyInjection\ClassResolver->getInstanceFromDefinition() (line 24 of /path/to/site/web/core/lib/Drupal/Core/DependencyInjection/ClassResolver.php).```

Any clues?

**Comment by aaron-capellic** [comment]
Nevermind, permissions issue.

**Comment by minnur** [comment]
Just in case if you're interested @aaron-capellic https://downloads.minnur.com/drupal/entity-reference-patterns
